[2025-05-16T15:27:36.082+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdc_pipeline.check_consumer scheduled__2025-05-16T15:17:28.355202+00:00 [queued]>
[2025-05-16T15:27:36.183+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdc_pipeline.check_consumer scheduled__2025-05-16T15:17:28.355202+00:00 [queued]>
[2025-05-16T15:27:36.186+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2025-05-16T15:27:36.352+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): check_consumer> on 2025-05-16 15:17:28.355202+00:00
[2025-05-16T15:27:36.399+0000] {standard_task_runner.py:57} INFO - Started process 5319 to run task
[2025-05-16T15:27:36.463+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'cdc_pipeline', 'check_consumer', 'scheduled__2025-05-16T15:17:28.355202+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/cdc_pipeline_dag.py', '--cfg-path', '/tmp/tmp6_x451a6']
[2025-05-16T15:27:36.478+0000] {standard_task_runner.py:85} INFO - Job 155: Subtask check_consumer
[2025-05-16T15:27:36.916+0000] {task_command.py:415} INFO - Running <TaskInstance: cdc_pipeline.check_consumer scheduled__2025-05-16T15:17:28.355202+00:00 [running]> on host 2325534d36fc
[2025-05-16T15:27:38.118+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdc_pipeline' AIRFLOW_CTX_TASK_ID='check_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-05-16T15:17:28.355202+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-16T15:17:28.355202+00:00'
[2025-05-16T15:27:38.120+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-16T15:27:38.122+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'nc -z kafka-connect 8083 || (echo "Kafka Connect not running!" && exit 1)']
[2025-05-16T15:27:38.137+0000] {subprocess.py:86} INFO - Output:
[2025-05-16T15:27:38.221+0000] {subprocess.py:93} INFO - nc: getaddrinfo for host "kafka-connect" port 8083: Name or service not known
[2025-05-16T15:27:38.224+0000] {subprocess.py:93} INFO - Kafka Connect not running!
[2025-05-16T15:27:38.224+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-16T15:27:38.323+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-16T15:27:38.327+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=cdc_pipeline, task_id=check_consumer, execution_date=20250516T151728, start_date=20250516T152736, end_date=20250516T152738
[2025-05-16T15:27:38.340+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 155 for task check_consumer (Bash command failed. The command returned a non-zero exit code 1.; 5319)
[2025-05-16T15:27:38.516+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-16T15:27:38.634+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
