[2025-05-16T14:09:54.761+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdc_pipeline.check_kafka scheduled__2025-05-16T13:57:28.355202+00:00 [queued]>
[2025-05-16T14:09:54.935+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdc_pipeline.check_kafka scheduled__2025-05-16T13:57:28.355202+00:00 [queued]>
[2025-05-16T14:09:54.935+0000] {taskinstance.py:1359} INFO - Starting attempt 3 of 4
[2025-05-16T14:09:55.147+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): check_kafka> on 2025-05-16 13:57:28.355202+00:00
[2025-05-16T14:09:55.254+0000] {standard_task_runner.py:57} INFO - Started process 1335 to run task
[2025-05-16T14:09:55.339+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'cdc_pipeline', 'check_kafka', 'scheduled__2025-05-16T13:57:28.355202+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/cdc_pipeline_dag.py', '--cfg-path', '/tmp/tmppgrt5p5c']
[2025-05-16T14:09:55.369+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask check_kafka
[2025-05-16T14:09:55.826+0000] {task_command.py:415} INFO - Running <TaskInstance: cdc_pipeline.check_kafka scheduled__2025-05-16T13:57:28.355202+00:00 [running]> on host 2325534d36fc
[2025-05-16T14:09:56.547+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdc_pipeline' AIRFLOW_CTX_TASK_ID='check_kafka' AIRFLOW_CTX_EXECUTION_DATE='2025-05-16T13:57:28.355202+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-16T13:57:28.355202+00:00'
[2025-05-16T14:09:56.551+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-16T14:09:56.552+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec kafka kafka-topics.sh --bootstrap-server kafka:9092 --list > /dev/null || exit 1']
[2025-05-16T14:09:56.723+0000] {subprocess.py:86} INFO - Output:
[2025-05-16T14:09:57.031+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2025-05-16T14:09:57.035+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-16T14:09:57.128+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-16T14:09:57.136+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=cdc_pipeline, task_id=check_kafka, execution_date=20250516T135728, start_date=20250516T140954, end_date=20250516T140957
[2025-05-16T14:09:57.234+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 43 for task check_kafka (Bash command failed. The command returned a non-zero exit code 1.; 1335)
[2025-05-16T14:09:57.416+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-16T14:09:57.729+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
