[2025-05-16T15:27:35.381+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdc_pipeline.check_kafka scheduled__2025-05-16T15:17:28.355202+00:00 [queued]>
[2025-05-16T15:27:35.470+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdc_pipeline.check_kafka scheduled__2025-05-16T15:17:28.355202+00:00 [queued]>
[2025-05-16T15:27:35.472+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2025-05-16T15:27:35.642+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): check_kafka> on 2025-05-16 15:17:28.355202+00:00
[2025-05-16T15:27:35.700+0000] {standard_task_runner.py:57} INFO - Started process 5317 to run task
[2025-05-16T15:27:35.720+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'cdc_pipeline', 'check_kafka', 'scheduled__2025-05-16T15:17:28.355202+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/cdc_pipeline_dag.py', '--cfg-path', '/tmp/tmpduakd33i']
[2025-05-16T15:27:35.752+0000] {standard_task_runner.py:85} INFO - Job 153: Subtask check_kafka
[2025-05-16T15:27:36.153+0000] {task_command.py:415} INFO - Running <TaskInstance: cdc_pipeline.check_kafka scheduled__2025-05-16T15:17:28.355202+00:00 [running]> on host 2325534d36fc
[2025-05-16T15:27:36.763+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdc_pipeline' AIRFLOW_CTX_TASK_ID='check_kafka' AIRFLOW_CTX_EXECUTION_DATE='2025-05-16T15:17:28.355202+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-16T15:17:28.355202+00:00'
[2025-05-16T15:27:36.774+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-16T15:27:36.775+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'nc -z kafka 9092']
[2025-05-16T15:27:36.826+0000] {subprocess.py:86} INFO - Output:
[2025-05-16T15:27:36.917+0000] {subprocess.py:93} INFO - nc: getaddrinfo for host "kafka" port 9092: Name or service not known
[2025-05-16T15:27:36.918+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-16T15:27:37.055+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-16T15:27:37.099+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=cdc_pipeline, task_id=check_kafka, execution_date=20250516T151728, start_date=20250516T152735, end_date=20250516T152737
[2025-05-16T15:27:37.251+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 153 for task check_kafka (Bash command failed. The command returned a non-zero exit code 1.; 5317)
[2025-05-16T15:27:37.317+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-16T15:27:37.842+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
